version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: db-professor-allocation
    volumes:
      - data:/var/lib/postgresql/db
    networks:
      - professor-allocation-net
    environment:
      POSTGRES_DB: db-professor-allocation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

volumes:
  data:
    external: false
networks:
  professor-allocation-net:
    driver: bridge